module.exports = {
  algorithm : 'aes256',
  api_key: 'e434699c',
  api_secret: 'eTNNejUT2sCPjlor',
  number: '918076125903',
  secret: 'grokonez-super-secret-key',
  ROLEs: ['SUPER_ADMIN', 'ADMIN','SOCIETY_MEMBER_OWNER','SOCIETY_MEMBER_TENANT','VENDOR'],
  url:'https://www.smsgateway.center/SMSApi/rest/send',
  userId:'jitkuk',
  password:'jit@4567',
  senderId:'CLNIND',
  sendMethod: 'simpleMsg',
  msgType: 'text',
  duplicateCheck: 'true',
  format: 'json',
  uploadFolderPath: './public',
  uploadImagePath: (__dirname, 'public/profilePictures/'),
  uploadDocumentPath: (__dirname, 'public/documents/'),
};